recipe_dir: conda.recipe
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - LICENSE
  - build-locally.py
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .circleci/config.yml
  - .github/workflows/main.yml
  - .github/workflows/webservices.yml
provider:
  linux: travis
  osx: azure
  win: None
  linux_ppc64le: None
  linux_aarch64: None
azure:
  force: False
  upload_packages: False
github:
  user_or_org: sparcians
  repo_name: map
