recipe_dir: conda.recipe
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - LICENSE
  - build-locally.py
  - .github
provider:
  linux: circle
  osx: azure
  win: None
  linux_ppc64le: None
  linux_aarch64: None
azure:
  force: False
  upload_packages: False
  store_build_artifacts: True
circle:
  upload_packages: False
github:
  user_or_org: sparcians
  repo_name: map
upload_on_branch: never_upload_packages
