# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360
  strategy:
    maxParallel: 8
    matrix:
      linux_boost_cpp1.69.0:
        CONFIG: linux_boost_cpp1.69.0
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_boost_cpp1.70.0:
        CONFIG: linux_boost_cpp1.70.0
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      linux_boost_cpp1.72.0:
        CONFIG: linux_boost_cpp1.72.0
        UPLOAD_PACKAGES: True
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
  - task: PublishTestResults@2
    inputs:
        testResultsFormat: 'cTest'
        testResultsFiles: '**/Test.xml'
        mergeTestResults: false # Unclear on impact of setting this true
        failTaskOnFailedTests: true
        publishRunAttachments: true # uploads xml files for possible inspection