# conda-build meta.yaml format docs are at:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
{% set name = "map" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
  string: {{ [PKG_BUILDNUM, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  # python2 is not supported by MAP
  # python<3.7 is not supported by conda-forge wxpython
  # Native Windows isn't supported either, use WSL or Docker
  skip: True # [win or py<37]
  script_env:
    - SYSTEM_DEFAULTWORKINGDIRECTORY # allow Azure variable into build.sh so that we can rescue our Test.xml files

requirements:
  build: # build-arch
    - cmake
    - cython
    - make
    - doxygen
    - python # specify here so that pinning from build matrix will be applied correctly
    - rsync
    - texlive-core
    # compiler('cxx') is defined at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml
    # see:
    #   https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-pinning
    #   https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#compiler-packages
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    # add duplicate clang dep per https://gitter.im/conda-forge/conda-forge.github.io?at=5e5feaf7ec7f8746aab200c4
    - clang 10
    - clangxx 10
    - llvm-tools 10
    - rsync
    # add runtime requirements for argos to make it easier to script
    # creation of a 'dev' environment that can also run Argos
    - matplotlib-base
    - numpy
    - pillow
    - pyyaml
    - wxpython
    - ipython
    - boost
  host:  # target-arch buildtime deps
    - boost-cpp
    - yaml-cpp
    - sqlite
    - hdf5
    - python
    - rapidjson
  run:
    - matplotlib-base
    - numpy
    - pillow
    - python
    - pyyaml
    - wxpython
    - ipython
    # duplicate required host libs to make it easier to script creation of run environent
    - boost-cpp
    - yaml-cpp
    - sqlite
    - hdf5
    - boost
  run_constrained:
    # make sure that mac has good enough SDK
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=feature#requiring-newer-macos-sdks
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

# TODO add post-packaging tests

about:
  home: https://github.com/sparcians/map
  summary: a set of classes, tools, and flows to aid in modeling/simulation of complex hardware for the purpose of performance analysis and design exploration
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/sparcians/map
  doc_url: https://github.com/sparcians/map
