on:
  pull_request:
    branches:
      - master

env:
  CACHE_VERSION: v1

name: Regress sparta on MacOS
jobs:
  build_test_job:
    strategy:
      # Strategy is a matrix of debug and release builds/regression
      matrix:
        os: [macos-15]
        BUILD_TYPE: [Release]
        COMPILER: [clang]

    name: macos-${{ matrix.BUILD_TYPE }}-${{matrix.COMPILER}}
    runs-on: ${{ matrix.os }}

    # Set up a global environment variable for build scripts
    env:
      SHINRO_BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      COMPILER:          ${{ matrix.COMPILER }}
      BUILD_TYPE:        ${{ matrix.BUILD_TYPE }}
      CCACHE_DIR:        /Users/runner/.ccache

    steps:
      # Get sparta
      - name: Clone sparta
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install missing packages to make everything build
      - name: Install packages needed for sparta
        run: |
          brew update
          brew install boost yaml-cpp rapidjson hdf5

      # Setup CCache to cache builds
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache-${{ github.ref_name }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache-master
            ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache

      # Setup fix CCache directory permissions
      - name: ccache macOS permission fix
        run: ./.github/actions/macos_perms.sh

      # Build
      - name: Build & Regress
        run: ./.github/actions/entrypoint.sh

      # Save error logs, etc
      - name: Save artifacts
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ErrorLogs-${{matrix.BUILD_TYPE}}-${{matrix.COMPILER}}
          path: sparta/Release
