# Generated by Django 3.0.4 on 2020-03-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedUser',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4096)),
                ('uuid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('layoutName', models.CharField(max_length=128)),
                ('layout', models.CharField(max_length=16384)),
                ('version', models.IntegerField(default=0)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LongFunctionCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionName', models.CharField(max_length=8192)),
                ('args', models.CharField(max_length=8192)),
                ('kwargs', models.CharField(max_length=1024)),
                ('execTime', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('dataUuid', models.CharField(max_length=128)),
                ('processor', models.CharField(max_length=128)),
                ('kwargs', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddConstraint(
            model_name='processorid',
            constraint=models.UniqueConstraint(fields=('processor', 'dataUuid', 'kwargs'), name='uniqueUUIDProcessor'),
        ),
        migrations.AddConstraint(
            model_name='layout',
            constraint=models.UniqueConstraint(fields=('uid', 'layoutName'), name='primaryKey'),
        ),
        migrations.AddConstraint(
            model_name='dataid',
            constraint=models.UniqueConstraint(fields=('path', 'uuid'), name='uniqueUUIDPath'),
        ),
    ]
